const {app,BrowserWindow,ipcMain,nativeTheme}=require('electron');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const os=require('node:os');
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'electron-lark-assistant-test-')));
const sourceRoot=process.env.JEV_TEST_APP_ROOT || path.resolve(__dirname,'../src');
const {spawn}=require('node:child_process');
const {createAnalysisService}=require(path.join(sourceRoot,'assistant/analysis-service'));
const {createJevClient}=require(path.join(sourceRoot,'assistant/jev-client'));
const {generateReplies}=require(path.join(sourceRoot,'assistant/codex-replies'));
let starts=[],phases=[],requests=[],cancelled=[],hold,release,failRank=false,generations=0,failGeneration=false,holdGeneration=false,generationPending=false;
const config={contextLimit:2,revision:1,jevApiKey:'synthetic-key',jevEndpoint:'https://example.invalid',codexPath:process.execPath,codexModel:''};
const jevClient=createJevClient({fetchImpl:async(_url,options)=>{
    const {state,questions}=JSON.parse(options.body);requests.push({state,questions});
    if(hold)await new Promise(r=>release=r);
    if(failRank && questions.best_reply)return {ok:false,status:503};
    const answers=require('./fixtures/jev-answers.cjs')(questions);
    return {ok:true,json:async()=>({answers})};
}});
const service=createAnalysisService({settingsStore:{readRuntime:async()=>({...config})},jevClient,generateReplies:async(c,input,options)=>{
    generations++;
    if(holdGeneration){generationPending=true;await new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(Error('已取消'),{code:'CANCELLED'})),{once:true}));}
    if(failGeneration)throw Object.assign(Error('合成改写失败'),{code:'CLI_EXIT'});
    return generateReplies(c,input,{...options,spawnImpl:(_binary,args,opts)=>spawn(process.execPath,[path.resolve(__dirname,options.skill?'fixtures/fake-codex-server.cjs':'fixtures/fake-codex.cjs'),...args],{...opts,env:{...process.env,ELECTRON_RUN_AS_NODE:'1'}})});
}});
ipcMain.handle('assistant:config',()=>({contextLimit:config.contextLimit,revision:config.revision,defaultReplyMode:config.defaultReplyMode || 'professional',skills:config.skills?.map(({id,name})=>({id,name})) || []}));
const progress=(event,snapshot)=>{phases.push(snapshot.stage);event.sender.send('assistant:progress',snapshot);};
ipcMain.on('assistant:start',(event,snapshot)=>{
    starts.push(snapshot);
    service.start(event.sender.id,snapshot,value=>progress(event,value));
});
ipcMain.on('assistant:cancel',(event,id)=>{cancelled.push(id);service.cancel(event.sender.id,id);});
ipcMain.on('assistant:clear',event=>service.cancelOwner(event.sender.id));
ipcMain.on('assistant:respond',(event,input)=>service.respond(event.sender.id,input));
ipcMain.on('assistant:retry-ranking',(event,id)=>service.retryRanking(event.sender.id,id,value=>progress(event,value)));
const deadline=setTimeout(()=>app.exit(1),45000);
app.whenReady().then(async()=>{
    const win=new BrowserWindow({webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:false,preload:path.join(sourceRoot,'chat-preload.js')}});
    await win.loadFile(path.resolve(__dirname,'fixtures/assistant-chat.html'));
    const run=script=>win.webContents.executeJavaScript(script);
    async function wait(script){for(let i=0;i<100;i++){if(typeof script==='function'?script():await run(script))return;await new Promise(r=>setTimeout(r,30));}throw Error(String(script));}
    async function click(selector,autoStart=true){const p=await run(`(()=>{window.testClickHandled=false;document.addEventListener('click',()=>{window.testClickHandled=true;},{once:true,capture:true});const el=document.querySelector(${JSON.stringify(selector)});el.scrollIntoView({block:'center'});const r=el.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p});await wait('window.testClickHandled');if(autoStart && selector.endsWith('.jev-trigger') && !config.skills?.length){await wait('!!document.querySelector(".jev-panel") && !Array.from(document.querySelectorAll(".jev-panel")).some(p=>p.textContent.includes("正在读取助手配置"))');if(await run('!!document.querySelector(".jev-start")'))await click('.jev-start');}}
    async function capture(name){if(!process.env.JEV_TEST_SCREENSHOTS)return;await run('document.querySelector(".jev-panel").scrollIntoView({block:"center"})');const rect=await run('(()=>{const r=document.querySelector(".jev-panel").getBoundingClientRect();return {x:Math.max(0,Math.ceil(r.x)),y:Math.max(0,Math.ceil(r.y)),width:Math.floor(Math.min(r.right,innerWidth)-Math.max(0,r.x)),height:Math.floor(Math.min(r.bottom,innerHeight)-Math.max(0,r.y))}})()');fs.mkdirSync(process.env.JEV_TEST_SCREENSHOTS,{recursive:true});fs.writeFileSync(path.join(process.env.JEV_TEST_SCREENSHOTS,name+'.png'),(await win.webContents.capturePage(rect)).toPNG());}
    try{
        await wait('document.querySelectorAll(".jev-trigger").length===4');
        assert.equal(await run('typeof require'),'undefined');
        assert.equal(await run('typeof window.assistant'),'undefined');
        await run('document.querySelector("#m4 .jev-trigger").click()');
        assert.equal(starts.length,0);
        await click('#m2 .jev-trigger');
        await wait('document.querySelector("#m2 .jev-error")');
        await click('#m2 .jev-trigger');
        assert.equal(await run('document.querySelectorAll("#m2 .jev-panel").length'),1);
        assert.equal(starts.length,0,'non-text messages never call models');
        await click('#m2 .jev-panel > .jev-action:last-child');
        await run('document.querySelector("#m3").dataset.senderId="alice";document.querySelector("#m3").dataset.senderName="合成甲";document.querySelector("#m4").dataset.senderId="bob";document.querySelector("#m4").dataset.senderName="合成乙"');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.length,1);
        assert.equal(starts[0].target.senderId,'bob');assert.equal(starts[0].candidates[0].senderId,'alice');
        assert((await run('document.querySelector("#m4 .jev-panel").textContent')).includes('本组推荐概率'));
        assert((await run('document.querySelector("#m4 .jev-panel").textContent')).includes('判断把握度'));
        assert.deepEqual(starts[0].candidates.map(m=>m.id),['m3']);
        assert.equal(starts[0].target.id,'m4');
        assert.equal(starts[0].target.replyToId,'m3');
        assert.equal(starts[0].target.text,'所选消息','quote preview is separate from target body');
        assert.equal(starts[0].conversationId,'chat1');
        assert.deepEqual(requests.find(r=>r.questions.intent).state.messages.map(m=>m.id),['m3'],'direct quote survives a low relevance score');
        await click('#m4 .jev-reply');
        await wait('document.querySelector("[contenteditable]").innerText.includes("还需要补充哪些信息？")');
        assert.deepEqual(phases,['filtering','judging','generating','ranking','complete']);
        assert(requests.every(r=>!JSON.stringify(r.state).includes('超过范围')));
        assert.equal(await run('document.querySelector("[contenteditable]").innerText'),'原有草稿\n还需要补充哪些信息？');
        assert.equal(await run('window.sent'),0);
        const cachedStarts=starts.length;
        await click('#m4 .jev-panel > .jev-action:last-child');
        await wait('!document.querySelector("#m4 .jev-panel") && document.querySelector("#m4 .jev-trigger").textContent==="查看分析"');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.length,cachedStarts,'reopening cached analysis makes no model call');
        nativeTheme.themeSource='light';
        await wait('matchMedia("(prefers-color-scheme: light)").matches');
        const lightBackground=await run('getComputedStyle(document.querySelector(".jev-panel")).backgroundColor');
        await capture('light');
        nativeTheme.themeSource='dark';
        await wait('getComputedStyle(document.querySelector(".jev-panel")).backgroundColor!=='+JSON.stringify(lightBackground));
        await capture('dark');
        nativeTheme.themeSource='system';
        await run('document.querySelector("#m4 .jev-panel").remove()');
        await wait('document.querySelector("#m4 .jev-reply")');
        await run('document.querySelector("#m4 .richTextContainer").firstChild.data="消息已编辑"');
        await wait('!document.querySelector(".jev-panel")');
        hold=true;
        await click('#m4 .jev-trigger');
        await wait(()=>starts.length===2);
        await click('#m4 .jev-trigger');
        assert.equal(starts.length,2,'duplicate active clicks are ignored');
        await run('document.querySelector("#m4").id="reused"');
        await wait('!document.querySelector(".jev-panel")');
        hold=false;release();
        await run('document.querySelector("#reused").id="m4"');
        failRank=true;
        await click('#m4 .jev-trigger');
        await wait('document.querySelector(".jev-error")?.textContent.includes("排序失败")');
        hold=true;
        await click('#m3 .jev-trigger');
        await wait(()=>starts.at(-1)?.messageId==='m3');
        const activeId=starts.at(-1).requestId;
        await run('document.querySelectorAll("#m4 .jev-action").forEach(b=>{if(b.textContent==="重试排序")b.id="retry-other"})');
        await click('#retry-other');
        win.webContents.send('assistant:settings-changed');
        await wait('!document.querySelector(".jev-panel")');
        assert.equal(cancelled.at(-1),activeId,'retrying an old result must not replace active request');
        hold=false;release();
        await click('#m4 .jev-trigger');
        await wait('document.querySelector(".jev-error")?.textContent.includes("排序失败")');
        const before=generations;failRank=false;
        await run('document.querySelectorAll(".jev-action").forEach(b=>{if(b.textContent==="重试排序")b.id="retry-rank"})');
        await click('#retry-rank');
        await wait('!document.querySelector(".jev-error") && document.querySelector(".jev-reply")');
        assert.equal(generations,before,'ranking retry does not regenerate');
        config.contextLimit=0;
        await click('#m3 .jev-trigger');
        await wait('document.querySelector("#m3 .jev-reply")');
        assert.equal(starts.at(-1).candidates.length,0);
        win.webContents.send('assistant:settings-changed');
        await wait('!document.querySelector(".jev-panel")');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.at(-1).target.replyToId,undefined,'N=0 does not expand scope for a quote');
        win.webContents.send('assistant:settings-changed');
        await wait('!document.querySelector(".jev-panel")');
        config.contextLimit=3;
        await run('document.querySelector("#m1 .richTextContainer").textContent="前序消息"');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.at(-1).target.replyToId,undefined,'duplicate quote text is ambiguous');
        await run('document.querySelector(".referencePreviewTitle__message span").firstChild.data="前序…"');
        await wait('!document.querySelector(".jev-panel")');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.at(-1).target.replyToId,undefined,'truncated quotes are not forced');
        await run('document.querySelector("[data-feed-id]").dataset.feedId="chat2"');
        await wait('!document.querySelector(".jev-panel")');
        await run(`document.querySelector('[data-feed-active]').dataset.feedActive='false';document.querySelectorAll('.jev-trigger').forEach(el=>el.remove());document.body.insertAdjacentHTML('afterbegin','<div class="feed-shortcut-list-inner"><div class="feed-shortcut-item"><div id="pin1" class="feed-item active">同名会话</div></div><div class="feed-shortcut-item"><div id="pin2" class="feed-item">同名会话</div></div></div>')`);
        await wait('document.querySelectorAll(".jev-trigger").length===4');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        const firstPinnedId=starts.at(-1).conversationId;
        assert.match(firstPinnedId,/^pinned:/);
        await run('document.querySelector("#pin1").classList.remove("active");document.querySelector("#pin2").classList.add("active")');
        await wait('!document.querySelector(".jev-panel")');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.notEqual(starts.at(-1).conversationId,firstPinnedId,'same-name pinned chats remain distinct');
        await run('document.querySelector("#pin2").classList.remove("active");document.querySelector("#pin1").classList.add("active")');
        await wait('!document.querySelector(".jev-panel")');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.at(-1).conversationId,firstPinnedId,'pinned identity is stable while mounted');
        config.skills=[{id:'synthetic-skill',name:'合成技能',path:path.resolve(__dirname,'fixtures/synthetic-skill/SKILL.md')}];
        config.codexReasoningEffort='high';
        win.webContents.send('assistant:settings-changed');
        await wait('!document.querySelector(".jev-panel")');
        const beforeSelection=starts.length;
        await click('#m4 .jev-trigger');
        await wait('!!document.querySelector("#m4 .jev-select")');
        assert.equal(starts.length,beforeSelection,'opening the skill picker never calls a model');
        await run(`document.querySelector('#m4 .jev-select').value='synthetic-skill';document.querySelector('#m4 .jev-select').dispatchEvent(new Event('change'));`);
        await click('#m4 .jev-action');
        await wait('document.querySelector("#m4 pre")?.textContent.includes("echo synthetic-skill")');
        assert.equal(starts.at(-1).skillId,'synthetic-skill');
        await run(`document.querySelectorAll('#m4 button').forEach(b=>{if(b.textContent==='允许本次')b.id='approve-skill'});document.querySelector('#approve-skill').click()`);
        assert.equal(await run('!!document.querySelector("#m4 .jev-reply")'),false,'programmatic approval is ignored');
        await click('#approve-skill');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert((await run('document.querySelector("#m4 .jev-panel").textContent')).includes('合成技能'));
        const skillGenerations=generations,skillQuestions=requests.filter(r=>r.questions.intent).length;
        await run(`document.querySelector('#m4 .jev-mode').value='pushback';document.querySelector('#m4 .jev-mode').dispatchEvent(new Event('change'));`);
        await click('#m4 .jev-switch-mode');await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(generations,skillGenerations+1);assert.equal(requests.filter(r=>r.questions.intent).length,skillQuestions,'switching mode reuses base judgment');
        assert.equal(starts.at(-1).modeId,'pushback');assert((await run('document.querySelector("#m4 .jev-panel").textContent')).includes('合成技能'));
        await run(`document.querySelector('#m4 .jev-mode').value='professional';document.querySelector('#m4 .jev-mode').dispatchEvent(new Event('change'));`);
        await click('#m4 .jev-switch-mode');await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(generations,skillGenerations+1,'cached mode makes no further CLI calls');
        failGeneration=true;
        await run(`document.querySelector('#m4 .jev-mode').value='firm';document.querySelector('#m4 .jev-mode').dispatchEvent(new Event('change'));`);
        await click('#m4 .jev-switch-mode');await wait('document.querySelector("#m4 .jev-error")');
        const failedGenerations=generations;failGeneration=false;
        await wait('!!document.querySelector("#m4 .jev-restore")');await click('#m4 .jev-restore');
        await wait('document.querySelector("#m4 .jev-reply")');assert.equal(generations,failedGenerations,'failure recovery must not rerun Skill');
        holdGeneration=true;
        await run(`document.querySelector('#m4 .jev-mode').value='firm';document.querySelector('#m4 .jev-mode').dispatchEvent(new Event('change'));`);
        await click('#m4 .jev-switch-mode');await wait(()=>generationPending);
        await run(`document.querySelectorAll('#m4 button').forEach(b=>{if(b.textContent==='取消')b.id='cancel-mode'})`);
        await click('#cancel-mode');holdGeneration=false;
        await wait('!!document.querySelector("#m4 .jev-restore")');const cancelledGenerations=generations;
        await click('#m4 .jev-restore');await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(generations,cancelledGenerations,'cancel recovery must not rerun Skill');
        const afterSkill=starts.length;
        await click('#m4 .jev-panel > .jev-action:last-child');
        await wait('!document.querySelector("#m4 .jev-panel")');
        await click('#m4 .jev-trigger');
        await wait('document.querySelector("#m4 .jev-reply")');
        assert.equal(starts.length,afterSkill);
        console.log('PASS assistant UI: full mock pipeline, trusted trigger, N=0/2/3, unique/ambiguous/truncated quotes, draft append, cancellation, stale edits/reused nodes, rank-only retry, settings/conversation cleanup, isolation');
        clearTimeout(deadline);app.exit(0);
    }catch(error){console.error(error);console.error(await run('Array.from(document.querySelectorAll(".jev-panel")).map(p=>({message:p.closest(".js-message-item")?.id,text:p.innerText}))'));app.exit(1);}
});
